# Generated by Django 4.2.1 on 2023-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('activity', models.CharField(max_length=225)),
                ('quantity', models.IntegerField(max_length=25)),
                ('img_file', models.CharField(max_length=225)),
            ],
        ),
    ]
