# Generated by Django 4.2.1 on 2023-05-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dokumen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='activity',
            field=models.CharField(max_length=225, verbose_name='Enter detail activity'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='img_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Enter full name'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='no',
            field=models.CharField(max_length=225, verbose_name='Enter of Number'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='quantity',
            field=models.IntegerField(max_length=25, verbose_name='Enter of Quantity'),
        ),
    ]
