# Generated by Django 4.2.1 on 2023-05-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_dokumen_activity_alter_dokumen_img_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
